### ISSUE TITLE
 contact page

### ISSUE THREAD

**Issue by mukulbbhardwaj** [mukulbbhardwaj/create-contact-card-HF22#2]
contact page

**Comment by c99SRS** [comment]
Hi @mukulbbhardwaj assign this to me

**Comment by Akash-moon** [comment]
Hello @mukulbbhardwaj sir, I want to contribute my efforts on this problem.
plz assign it to me under hacktober.

**Comment by mukulbbhardwaj** [comment]
> Hello @mukulbbhardwaj sir, I want to contribute my efforts on this problem.
> plz assign it to me under hacktober.
> 

Do it and create a PR

**Comment by Akash-moon** [comment]
ok I'll try to do it ASAP

**Comment by Akash-moon** [comment]
Done , I have send you a PR , Please Merge it by labeling hacktoberfest-accepted .
Thank you so much.

**Comment by Amisha2004** [comment]
Can I also do this issue??please assign me.
